[package]
name = "kumquat_virtio"
version = "0.1.61"
authors = ["Android Open Source Project"]
edition = "2021"
description = "Handling virtio multi-media protocols via a Rust server"
license = "BSD-3-Clause"

[[bin]]
name = "kumquat"
path = "src/main.rs"

[features]
gfxstream = ["rutabaga_gfx/gfxstream"]

[dependencies]
mesa3d_util = { path = "../../third_party/mesa3d/src/util/rust/", version = "0.1.71" }
mesa3d_protocols = { path = "../../third_party/mesa3d/src/virtio/protocols", version = "0.1.7" }
rutabaga_gfx = { path = "../../", version = "0.1.61"}
zerocopy = { version = "0.8.13", features = ["derive"] }
log = "0.4"
remain = "0.2"
thiserror = "1.0.23"
clap = { version = "4.1.8", features = ["derive"] }
